abstract: CJK text analyzer for Plucene
author: Yung-chung Lin <xern@cpan.org>
build_requires:
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.51
license: perl
name: Plucene-Analysis-CJKAnalyzer
no_index:
  directory:
    - inc
    - t
requires:
  Plucene: 0
version: 0.02
